version: "3.9"
name: inception

services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - site:/var/www/html
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
    depends_on:
      - wordpress
#    secrets:
#      - server-certificate

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      args:
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - site:/var/www/html
    networks:
      - inception
    #ports:
    #  - "9000:9000"
    restart: on-failure
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    #ports:
    #  - "3306:3306"
    restart: on-failure

volumes:

  db:
    name: db
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/db
      o: bind

  site:
    name: site
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/site
      o: bind

#volumes:
#  mysql_data:
#    driver: local
#    driver_opts:
#      type: none
#      device: /srv/docker/mysql-data
#      o: bind

networks:
  inception:
    name: inception
    driver: bridge

#hostname: pthomas
#domainname: 42.fr
#init:

#    driver: flocker
#    driver_opts:
#      size: "10GiB"

#secrets:
#  server-certificate:
#    external: true