version: "3.9"
name: inception

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
      # args:
      #   - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      #   - MYSQL_DATABASE=$MYSQL_DATABASE
      #   - MYSQL_USER=$MYSQL_USER
      #   - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      env_file:
        - .env
      # args:
      #   - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      #   - WORDPRESS_DB_USER=$MYSQL_USER
      #   - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      #   - WORDPRESS_DB_HOST=$MYSQL_HOST
    volumes:
      - site:/var/www/html
    networks:
      - inception
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - site:/var/www/html
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
    depends_on:
      - wordpress
    secrets:
      - ssl-certificate
      - ssl-key

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/db
      o: bind

  site:
    name: site
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/site
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

secrets:
    ssl-certificate:
      file: ./conf/inception_ssl.crt
    ssl-key:
      file: ./conf/inception_ssl.key
