version: "3.9"
name: inception

services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure
#    secrets:
#      - server-certificate

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      args:
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
    env_file:
      - .env
#    volumes:
#      - wp-site:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    #ports:
    #  - "9000:443"

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
    env_file:
      - .env
#    volumes:
#      - wp-db:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    #ports:
    #  - "3306:3306"

#volumes:
#  wp-db:
#  wp-site:

networks:
  inception: {}

#hostname: pthomas
#domainname: 42.fr
#init:

#    driver: flocker
#    driver_opts:
#      size: "10GiB"

#secrets:
#  server-certificate:
#    external: true
