# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pthomas <pthomas@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/04/15 11:51:05 by pthomas           #+#    #+#              #
#    Updated: 2022/05/24 20:46:53 by pthomas          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

FROM	debian:buster

# SYSTEM UPDATE AND DEPENDENCIES
RUN		apt-get update -y && apt-get upgrade -y

# PORTSENTRY
RUN		apt-get install -y fail2ban \
&&		service fail2ban start && service fail2ban stop

# CONFIG
COPY	./conf/jail.conf /etc/fail2ban
RUN		touch /var/log/auth.log

# START
ENTRYPOINT	["fail2ban-server", "-f"]
